Get http://localhost:3001/


###
POST http://localhost:3001/api/user
content-type: application/json

{
    "name": "user 10",
    "email":"vaibhav@gmail.com",
    "password":"12349876"

}


###
POST http://localhost:3001/api/auth/login
content-type: application/json

{ 
    "email":"vibhav111@gmail.com",
    "password":"124567890"
}

